services:
  mariadb:
    image: mariadb:11.1.2
    restart: unless-stopped
    volumes:
      - ./infra/volumes/dev/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"

  php:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./infra/volumes/dev/composer:/root/.composer
      - ./infra/php/dev/project.ini:/usr/local/etc/php/conf.d/project.ini:ro
      - ./app:/var/www/app
    environment:
      APP_ENV: dev
    depends_on:
      - mariadb
    tty: true

  nginx:
    image: nginx:latest
    volumes:
      - ./infra/volumes/dev/logs/nginx:/var/log/nginx
      - ./infra/nginx/dev/virtualhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/app
    ports:
      - "80:80"
    depends_on:
      - php
    tty: true

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - '8888:80'
      - '443:443'
    volumes:
      - ./infra/volumes/dev/mercure-data:/data
      - ./infra/volumes/dev/mercure-config:/config

  mailcatcher:
    restart: on-failure
    image: schickling/mailcatcher
    ports: [ 1025, 1080:1080 ]
